# Generated by Django 6.0.5 on 2026-06-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application',
            new_name='applicant',
        ),
    ]
